# Spring Boot Configuration
spring:
  application:
    name: Moroccan Cooking Companion
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  threads:
    virtual:
      enabled: true
  mustache:
    check-template-location: false
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json


# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Vaadin Configuration
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

logging:
  level:
    org:
      atmosphere: warn
